### PR TITLE
Change Chips to buttons

### PR DESCRIPTION
**Pull request by coliff**
This PR changes the chips from divs to buttons which gives them a focus state and allows user to tab to them.

### CODE REVIEW

**Review by msankaran0712 — CHANGES_REQUESTED** [review]
image

Why do the chips inside Table get a border colour on click?

**Comment by coliff** [comment]
> Why do the chips inside Table get a border colour on click?

Because they were not previously focusable, and now they are. You can see by comparing to: https://modus.trimble.com/components/web/chips/styles/ - the chips are not focusable as they aren't buttons.

Note that focus state styles are not currently specified in styleguide or on Figma.

**Comment by msankaran0712** [comment]
> > Why do the chips inside Table get a border colour on click?
> 
> Because they were not previously focusable, and now they are. You can see by comparing to: https://modus.trimble.com/components/web/chips/styles/ - the chips are not focusable as they aren't buttons.
> 
> Note that focus state styles are not currently specified in styleguide or on Figma.

@soniakaukonen is it possible to confirm the focus style for chips?

**Comment by msankaran0712** [comment]
> > > Why do the chips inside Table get a border colour on click?
> > 
> > 
> > Because they were not previously focusable, and now they are. You can see by comparing to: https://modus.trimble.com/components/web/chips/styles/ - the chips are not focusable as they aren't buttons.
> > Note that focus state styles are not currently specified in styleguide or on Figma.
> 
> @soniakaukonen is it possible to confirm the focus style for chips?

As discussed with @soniakaukonen we will have to wait for @egunther39 to discuss the focus styles

**Review by msankaran0712 — APPROVED** [review]

**Comment by coliff** [comment]
Thanks for approving. I realize the focus states may change but I think it's important for now to at least get them working as imtending. :-)

**Pull request merged**
